name: example
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  device_preview: 1.2.0
  equatable: 2.0.7
  expandable: 5.0.1
  faker: 2.2.0
  flutter_bloc: 9.1.0
  go_router: 14.8.1
  nice_flutter_kit:
    path: ../
  reactive_forms: 17.0.1

dependency_overrides:
  path_provider_windows: 2.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/localizations/
