name: example
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: 8.0.1
  go_router: 3.0.4
  nice_flutter_kit:
    path: ../
  reactive_forms: 11.0.1
  expandable: ^5.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
