name: example
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  device_preview: 1.1.0
  expandable: 5.0.1
  faker: 2.0.0
  flutter_bloc: 8.0.1
  go_router: 3.1.0
  nice_flutter_kit:
    path: ../
  reactive_forms: 13.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/localizations/
