name: example
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  device_preview: 1.1.0
  equatable: 2.0.5
  expandable: 5.0.1
  faker: 2.1.0
  flutter_bloc: 8.1.2
  go_router: 7.0.1
  nice_flutter_kit:
    path: ../
  reactive_forms: 14.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/localizations/
